- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  vars_files:
    - keys.yml
  roles:
    - openstack_infra

- hosts: cluster
  gather_facts: false
  vars_files:
    - "global_vars.yml"
  roles:
    - cluster

- hosts: master
  vars_files:
    - "global_vars.yml"
  roles:
    - master
    - common

- hosts: workers
  vars_files:
    - "global_vars.yml"
  roles:
    - workers
    - common

- hosts: master
  vars_files:
    - "global_vars.yml"
  roles:
    - gantsign.golang
    - csi

- hosts: devstack
  roles:
    - devstack
