- name: initialize kubeadm on master
  become: yes
  shell: |
    kubeadm init --pod-network-cidr=10.244.0.0/16 \
        --token={{kubernetes_token }} \
        --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
        --apiserver-cert-extra-sans={{ inventory_hostname }}
  args:
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: ensure that /home/centos/.kube exists
  become: yes
  file:
    state: directory
    path: /home/centos/.kube
    owner: centos
    group: centos
    mode: 0775

- name: install kubeconfig in /home/centos/.kube
  become: yes
  command: install -o centos -g centos -m 0775 /etc/kubernetes/admin.conf /home/centos/.kube/config

- name: replace the master node's internal/host network IP with floating IP
  replace:
    path: /home/centos/.kube/config
    after: 'server:'
    regexp: 'https://[0-9.]+:6443'
    replace: "https://{{ inventory_hostname }}:6443"

- name: get local kubeconfig.conf
  fetch:
    src: /home/centos/.kube/config
    dest: kubeconfig.conf
    flat: yes

- name: create flannel network
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
